---
abstract: ~
author:
  - 'Yo-An Lin <cornelius.howl {at} gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 6.36
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Plack-App-JenkinsNotification
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Jenkins::NotificationListener: 0.04
  Net::Jenkins: 0.04
  Plack: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.02
